import Fastify from 'fastify';import cookie from '@fastify/cookie';import cors from '@fastify/cors';import rateLimit from '@fastify/rate-limit';import {Server} from 'socket.io';import Database from 'better-sqlite3';import argon2 from 'argon2';import crypto from 'node:crypto';import {z} from 'zod';import {prepareAction,resolveRound,type GameState} from '@game/engine';import type {TurnAction} from '@game/protocol';
const app=Fastify({logger:true});await app.register(cors,{origin:process.env.WEB_ORIGIN??'http://localhost:5173',credentials:true});await app.register(cookie);await app.register(rateLimit,{max:100,timeWindow:'1 minute'});
const db=new Database(process.env.DB_FILE??'game.db');db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL);`);
const authSchema=z.object({username:z.string().trim().min(3).max(32).regex(/^[\p{L}\p{N}_-]+$/u),password:z.string().min(8).max(128)});
const hashToken=(x:string)=>crypto.createHash('sha256').update(x).digest('hex');
function user(req:any){const t=req.cookies.session;if(!t)return null;return db.prepare('SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').get(hashToken(t),Date.now()) as {id:string;username:string}|undefined}
async function session(reply:any,userId:string){const token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hashToken(token),userId,Date.now()+30*864e5);reply.setCookie('session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:30*86400});}
app.post('/api/register',{config:{rateLimit:{max:8,timeWindow:'1 minute'}}},async(req,reply)=>{const v=authSchema.safeParse(req.body);if(!v.success)return reply.code(400).send({error:'输入不合法'});const id=crypto.randomUUID();try{db.prepare('INSERT INTO users VALUES(?,?,?)').run(id,v.data.username.toLowerCase(),await argon2.hash(v.data.password,{type:argon2.argon2id}));await session(reply,id);return {id,name:v.data.username}}catch{return reply.code(409).send({error:'用户名已存在'})}});
app.post('/api/login',{config:{rateLimit:{max:8,timeWindow:'1 minute'}}},async(req,reply)=>{const v=authSchema.safeParse(req.body);if(!v.success)return reply.code(400).send({error:'用户名或密码错误'});const row=db.prepare('SELECT * FROM users WHERE username=?').get(v.data.username.toLowerCase()) as any;if(!row||!await argon2.verify(row.password_hash,v.data.password))return reply.code(401).send({error:'用户名或密码错误'});await session(reply,row.id);return {id:row.id,name:row.username}});
app.get('/api/me',async(req,reply)=>user(req)??reply.code(401).send({error:'未登录'}));
const games=new Map<string,{state:GameState;host:string;actions:Map<string,TurnAction>;timer?:NodeJS.Timeout;started:boolean}>();
app.post('/api/games',async(req,reply)=>{const u=user(req);if(!u)return reply.code(401).send();const id=crypto.randomUUID();games.set(id,{host:u.id,started:false,actions:new Map(),state:{id,round:1,players:[{id:u.id,name:u.username,armor:0,alive:true,moves:[],effects:[]}]}});return {id}});
app.post('/api/games/:id/join',async(req:any,reply)=>{const u=user(req);const g=games.get(req.params.id);if(!u||!g)return reply.code(404).send();if(g.started||g.state.players.length>=12)return reply.code(409).send({error:'房间已开始或已满'});if(!g.state.players.some(p=>p.id===u.id))g.state.players.push({id:u.id,name:u.username,armor:0,alive:true,moves:[],effects:[]});return g.state});
const http=await app.listen({port:Number(process.env.PORT??3000),host:'0.0.0.0'});const io=new Server(app.server,{cors:{origin:process.env.WEB_ORIGIN??'http://localhost:5173',credentials:true}});
function startRound(id:string){const g=games.get(id);if(!g)return;g.timer=setTimeout(()=>finish(id),5000);io.to(id).emit('round-open',{round:g.state.round,deadlineAt:Date.now()+5000,state:g.state});}
function finish(id:string){const g=games.get(id);if(!g)return;const prepared=[];for(const a of g.actions.values())try{prepared.push(prepareAction(g.state,a))}catch{}const r=resolveRound(g.state,prepared);g.state=r.state;g.actions.clear();io.to(id).emit('round-result',{state:g.state,events:r.events});if(g.state.players.filter(p=>p.alive).length>1)startRound(id)}
io.use((socket,next)=>{const raw=socket.handshake.headers.cookie??'';const t=raw.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8);const u=t&&db.prepare('SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').get(hashToken(decodeURIComponent(t)),Date.now()) as any;if(!u)return next(Error('unauthorized'));socket.data.user=u;next()});
io.on('connection',socket=>{socket.on('join-game',(id:string,ack:any)=>{const g=games.get(id);if(!g||!g.state.players.some(p=>p.id===socket.data.user.id))return ack?.({error:'不可加入'});socket.join(id);ack?.({state:g.state})});socket.on('start-game',(id:string,ack:any)=>{const g=games.get(id);if(!g||g.host!==socket.data.user.id||g.started)return ack?.({error:'不可开始'});g.started=true;startRound(id);ack?.({ok:true})});socket.on('submit-action',(raw:TurnAction,ack:any)=>{const g=games.get(raw.gameId);if(!g||!g.started||raw.round!==g.state.round||raw.playerId!==socket.data.user.id||g.actions.has(raw.playerId))return ack?.({error:'动作无效或已提交'});try{prepareAction(g.state,raw);g.actions.set(raw.playerId,raw);ack?.({ok:true})}catch(e){ack?.({error:(e as Error).message})}})});
app.log.info(`listening ${http}`);
